name: Update Manual Release
on:
  release:
    types: [created]
jobs:
  update-release:
    if: |
      github.event.release.draft == false &&
      github.event.action == 'created'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract release notes
        id: extract-notes
        run: |
          # 使用更可靠的 tag_name 获取版本
          RELEASE_VERSION="${github.event.release.tag_name}"

          # 改进的 CHANGELOG 解析（兼容更多格式）
          if [ -f CHANGELOG.md ]; then
            RELEASE_NOTES=$(awk -v version="$RELEASE_VERSION" '
              BEGIN {flag=0; count=0}
              /^## \[?v?/ && ($2 == version || $3 == version) {flag=1; next}
              /^## \[?v?/ && flag {exit}
              flag {print; count++}
              END {if (count==0) exit 1}
            ' CHANGELOG.md)

            if [ $? -ne 0 ]; then
              echo "⚠️ CHANGELOG.md 中未找到匹配版本，使用默认说明"
              RELEASE_NOTES="${{ github.event.release.body }}"
            fi
          else
            RELEASE_NOTES="${{ github.event.release.body }}"
          fi

          # 修复换行符问题
          NOTES_CONTENT=$(printf "## Release v%s\n%s\n\n_自动从 CHANGELOG.md 更新_" "$RELEASE_VERSION" "$RELEASE_NOTES")

          echo "version=$RELEASE_VERSION" >> $GITHUB_OUTPUT
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          echo "$NOTES_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          name: Release v${{ steps.extract-notes.outputs.version }}
          body: ${{ steps.extract-notes.outputs.notes }}
          draft: false
          prerelease: ${{ github.event.release.prerelease }}
          release_id: ${{ github.event.release.id }}
