name: Update Changelog and Version

on:
  push:
    paths:
      - 'CHANGELOG'

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run changelog converter
        run: node scripts/convert-changelog.js
        env:
          GITHUB_ACTIONS: 'true'

      - name: Get branch name
        id: branch
        run: |
          echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Commit changes
        id: commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add src/lib/changelog.ts src/lib/version.ts VERSION.txt
          git commit -m "chore: update changelog and version files [skip ci]" || echo "No changes to commit"
          echo "changes_made=$([[ -n $(git status --porcelain) ]] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT

      - name: Push changes
        if: steps.commit.outputs.changes_made == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.branch.outputs.branch_name }}
